import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";

import { calls } from "../../../../core/calls";

import {
  setMissions,
  setModal,
  setSnackBarText,
} from "../../../../core/ConfigureStore";

import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import IconButton from "@mui/material/IconButton";

import CloseSharpIcon from "@mui/icons-material/CloseSharp";
import RocketLaunchIcon from "@mui/icons-material/RocketLaunch";

import TextField from "@mui/material/TextField";
import FormGroup from "@mui/material/FormGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import InputLabel from "@mui/material/InputLabel";

import { makeStyles, useTheme } from "@mui/styles";
import useMediaQuery from "@mui/material/useMediaQuery";

const useStyles = makeStyles((theme) => ({
  Modal: {
    margin: theme.headHeights[1],
    [theme.breakpoints.down("xs")]: {
      margin: "6px",
    },
    "& .MuiDialog-container": {
      height: "unset !important",
      transform: "translateX(-50%) translateY(-50%)",
      left: "50%",
      top: "50%",
      position: "absolute",
    },
  },
  contents: {
    background: theme.palette.primary.main,
    height: "100%",
    width: "700px",
    maxWidth: "700px !important",
  },
  heading: {
    height: theme.headHeights[2],
    boxSizing: "border-box",
    background: theme.palette.swatches.p[0],
    borderBottom: `1px solid ${theme.palette.swatches.grey[800]}`,
    padding: `4px ${theme.spacing(2)} 4px ${theme.spacing(4)} !important`,
  },
  title: {
    padding: `8px 0px`,
    fontSize: theme.typography.pxToRem(16),
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  content: {
    padding: "8px 16px 16px 16px !important",
    height: `calc(100% - ${theme.headHeights[2]}px)`,
  },
  closeIcon: {
    padding: theme.spacing(1.5),
    height: "100%",
    margin: "4px 0px",
  },
  flexBetween: {
    display: "flex",
    justifyContent: "space-between",
  },
  subtitle: {
    fontSize: "14px !important",
    width: "100%",
    marginBottom: "8px !important",
    color: theme.palette.swatches.grey[300],
    letterSpacing: "0.2px",
  },
  subtitle2: {
    fontSize: "12px !important",
    fontStyle: "italic",
    width: "100%",
    marginBottom: "8px !important",
    color: theme.palette.swatches.grey[400],
  },
  missionNameInput: {
    width: "100%",
    margin: "8px 0px 4px 0px !important",
  },
  backgroundIcon: {
    margin: "7px 8px 0px 0px",
  },
  planetDropdown: {
    width: "100%",
    margin: "8px 0px 4px 0px !important",
  },
  divider: {
    margin: "24px 0px 16px 0px !important",
    borderTop: `1px solid ${theme.palette.swatches.grey[700]}`,
  },
  sectionTitle: {
    fontSize: "14px !important",
    fontWeight: "bold !important",
    marginTop: "8px !important",
    marginBottom: "8px !important",
    color: theme.palette.swatches.grey[200],
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  explanationBox: {
    backgroundColor: theme.palette.swatches.grey[900],
    border: `1px solid ${theme.palette.swatches.grey[700]}`,
    borderRadius: "4px",
    padding: "12px",
    marginBottom: "12px",
    "& ul": {
      margin: "8px 0px",
      paddingLeft: "20px",
    },
    "& li": {
      marginBottom: "6px",
      fontSize: "13px",
      color: theme.palette.swatches.grey[300],
    },
  },
  explanationTitle: {
    fontSize: "14px !important",
    fontWeight: "bold !important",
    marginBottom: "8px !important",
    color: `${theme.palette.swatches.r[3]} !important`,
  },
  explanationText: {
    fontSize: "13px !important",
    color: `${theme.palette.swatches.grey[100]} !important`,
    marginBottom: "12px !important",
  },
}));

const PLANET_RADII = {
  Earth: { major: 6371008, minor: 6371008 },
  Mars: { major: 3396190, minor: 3396190 },
  "The Moon": { major: 1737400, minor: 1737400 },
};

const MODAL_NAME = "newMission";
const NewMissionModal = (props) => {
  const {} = props;
  const c = useStyles();

  const modal = useSelector((state) => state.core.modal[MODAL_NAME]);

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"));

  const dispatch = useDispatch();

  const [missionName, setMissionName] = useState("");
  const [createDir, setCreateDir] = useState(true);
  const [selectedPlanet, setSelectedPlanet] = useState("Earth");
  const [setupReferenceMission, setSetupReferenceMission] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState("");

  // Auto-generate mission name when Reference Mission mode is enabled
  useEffect(() => {
    if (setupReferenceMission) {
      const name = "Reference-Mission"; // Static name instead of timestamp
      setAutoGeneratedName(name);
      setMissionName(name);
    } else {
      setAutoGeneratedName("");
    }
  }, [setupReferenceMission]);

  const handleClose = () => {
    // close modal
    dispatch(setModal({ name: MODAL_NAME, on: false }));
  };
  const handleSubmit = () => {
    if (missionName == null || missionName === "") {
      dispatch(
        setSnackBarText({
          text: "Please enter a mission name.",
          severity: "error",
        }),
      );
      return;
    }

    const planetRadius = PLANET_RADII[selectedPlanet];

    // Build the config with just the radius values
    const config = {
      msv: {
        radius: {
          major: planetRadius.major,
          minor: planetRadius.minor,
        },
      },
    };

    // Prepare payload
    const payload = {
      mission: missionName,
      makedir: createDir || setupReferenceMission,
      setupReferenceMission: setupReferenceMission,
    };

    // Only send config if not in Reference Mission mode
    if (!setupReferenceMission) {
      payload.config = config;
    }

    calls.api(
      "add",
      payload,
      (res) => {
        calls.api(
          "missions",
          null,
          (res) => {
            dispatch(setMissions(res.missions));

            dispatch(
              setSnackBarText({
                text:
                  res.message ||
                  `Successfully added new mission: ${missionName}`,
                severity: "success",
              }),
            );
            // reset fields
            setMissionName("");
            setCreateDir(true);
            setSelectedPlanet("Earth");
            setSetupReferenceMission(false);

            // and then close
            handleClose();
          },
          (res) => {
            dispatch(
              setSnackBarText({
                text: res?.message || "Failed to requery missions.",
                severity: "error",
              }),
            );

            // reset fields
            setMissionName("");
            setCreateDir(true);
            setSelectedPlanet("Earth");
            setSetupReferenceMission(false);

            // and then close
            handleClose();
          },
        );
      },
      (res) => {
        dispatch(
          setSnackBarText({
            text: res?.message || "Failed to make new mission.",
            severity: "error",
          }),
        );
      },
    );
  };

  return (
    <Dialog
      className={c.Modal}
      fullScreen={isMobile}
      open={modal !== false}
      onClose={handleClose}
      aria-labelledby="responsive-dialog-title"
      PaperProps={{
        className: c.contents,
      }}
    >
      <DialogTitle className={c.heading}>
        <div className={c.flexBetween}>
          <div className={c.flexBetween}>
            <RocketLaunchIcon className={c.backgroundIcon} />
            <div className={c.title}>Make a New Mission</div>
          </div>
          <IconButton
            className={c.closeIcon}
            title="Close"
            aria-label="close"
            onClick={handleClose}
          >
            <CloseSharpIcon fontSize="inherit" />
          </IconButton>
        </div>
      </DialogTitle>
      <DialogContent className={c.content}>
        <Typography className={c.subtitle}>
          Missions are separately configurable MMGIS map interfaces.
        </Typography>
        <TextField
          className={c.missionNameInput}
          label="Mission Name"
          variant="filled"
          value={missionName}
          onChange={(e) => {
            setMissionName(e.target.value);
          }}
          disabled={setupReferenceMission}
          placeholder={setupReferenceMission ? autoGeneratedName : ""}
        />
        <Typography className={c.subtitle2}>
          {`A new and unique name for a mission. No special characters allowed and it should not start with a number.`}
        </Typography>
        <FormControl className={c.planetDropdown} variant="filled">
          <InputLabel>Planet</InputLabel>
          <Select
            value={selectedPlanet}
            onChange={(e) => setSelectedPlanet(e.target.value)}
            label="Planet"
            disabled={setupReferenceMission}
          >
            <MenuItem value="Earth">Earth</MenuItem>
            <MenuItem value="Mars">Mars</MenuItem>
            <MenuItem value="The Moon">The Moon</MenuItem>
          </Select>
        </FormControl>
        <Typography className={c.subtitle2}>
          {`Select the planet to set the default radius values for this mission. You can always change this later.`}
        </Typography>
        <FormGroup>
          <FormControlLabel
            control={
              <Checkbox
                checked={createDir || setupReferenceMission}
                onChange={(e) => {
                  setCreateDir(!createDir);
                }}
                disabled={setupReferenceMission}
              />
            }
            label="Create a /Missions/{Mission Name} directory"
          />
        </FormGroup>
        <Typography className={c.subtitle2}>
          {`Layer, Tiles and Data for this mission can be stored in /Missions/{Mission Name} directory.
            Whenever a non-absolute URL is found in this mission's configuration, it will be treated as relative to this folder regardless of whether this folder exists.`}
        </Typography>

        <div className={c.divider}></div>

        <Typography className={c.sectionTitle}>
          Reference Mission Demo
        </Typography>

        <div className={c.explanationBox}>
          <Typography className={c.explanationTitle}>
            What is the Reference Mission?
          </Typography>
          <Typography className={c.explanationText}>
            The Reference Mission is a comprehensive demo showcasing all MMGIS
            features, layer types, tools, and configuration options.
          </Typography>
          <ul>
            <li>
              <strong>Purpose:</strong> Reference, demonstration, development
              and testing
            </li>
            <li>
              <strong>Includes:</strong> 20+ sample layers, 14 interactive
              tools, and comprehensive documentation
            </li>
            <li>
              <strong>Deployed to:</strong>{" "}
              <code>Missions/Reference-Mission/</code> (always overwritten)
            </li>
            <li>
              <strong>Source:</strong> Blueprint template at{" "}
              <code>blueprints/Missions/Reference-Mission/</code>
            </li>
            <li>
              <strong>Updates:</strong> Checking this will{" "}
              <strong>completely replace</strong> any existing Reference-Mission
              with its latest blueprint
            </li>
          </ul>
        </div>

        <FormGroup>
          <FormControlLabel
            control={
              <Checkbox
                checked={setupReferenceMission}
                onChange={(e) => {
                  setSetupReferenceMission(!setupReferenceMission);
                }}
              />
            }
            label="Setup Reference Mission Demo (creates or updates 'Reference-Mission')"
          />
        </FormGroup>
        <Typography className={c.subtitle2}>
          {setupReferenceMission
            ? `⚠️ This will DELETE and recreate the entire Missions/Reference-Mission directory with the latest blueprint. Mission will be named: ${autoGeneratedName}`
            : "Check this to create or overwrite the Reference Mission demo with the latest blueprint data."}
        </Typography>
      </DialogContent>
      <DialogActions>
        <Button
          className={c.addSelected}
          variant="contained"
          onClick={handleSubmit}
        >
          Make Mission
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default NewMissionModal;
