export const config = {
  rows: [
    {
      name: "Basic Information",
      components: [
        {
          field: "temp.editStacCollection.id",
          name: "Collection ID",
          description:
            "Identifier for the Collection. This cannot be changed after creation.",
          type: "text",
          width: 12,
          disabled: true,
        },
        {
          field: "temp.editStacCollection.title",
          name: "Title",
          description: "A short descriptive one-line title for the Collection.",
          type: "text",
          width: 6,
        },
        {
          field: "temp.editStacCollection.description",
          name: "Description",
          description:
            "Detailed multi-line description to fully explain the Collection.",
          type: "text",
          width: 12,
        },
        {
          field: "temp.editStacCollection.license",
          name: "License",
          description:
            "License(s) of the data collection as SPDX License identifier, SPDX License expression, or other.",
          type: "text",
          width: 6,
        },
        {
          field: "temp.editStacCollection.keywords",
          name: "Keywords",
          description: `Comma-separated list of keywords describing the Collection.`,
          type: "textarray",
          width: 6,
        },
      ],
    },
    {
      name: "Spatial & Temporal Extent",
      components: [
        {
          field: "temp.editStacCollection.extent.spatial.bbox",
          name: "Spatial Extent Bounding Box",
          description:
            "Potential spatial extents covered by the Collection. Format: [[-180.0, -90.0, 180.0, 90.0]]",
          type: "text",
          width: 12,
        },
        {
          field: "temp.editStacCollection.extent.temporal.interval",
          name: "Temporal Extent Interval",
          description: `Potential temporal extents covered by the Collection. Each inner array consists of exactly two elements, either a UTC date timestamp or null. Format: [["1970-01-01T00:00:00Z", null]]`,
          type: "text",
          width: 12,
        },
      ],
    },
    {
      name: "Links & Providers",
      components: [
        {
          field: "temp.editStacCollection.links",
          name: "Links",
          description: "A list of references to other documents.",
          type: "objectarray",
          width: 12,
          object: [
            {
              field: "title",
              name: "Title",
              description:
                "A human readable title to be used in rendered displays of the link.",
              type: "text",
              width: 8,
            },
            {
              field: "href",
              name: "HREF",
              description:
                "The actual link in the format of an URL. Relative and absolute links are both allowed. Trailing slashes are significant.",
              type: "text",
              width: 8,
            },
            {
              field: "rel",
              name: "Relations",
              description:
                "STAC Entities use a variety of rel types in the Link Object, to describe the exact nature of the link between the STAC object and the entity it is linking to. It is recommended to use the official IANA Link Relation Types (https://www.iana.org/assignments/link-relations/link-relations.xhtml) where possible.",
              type: "dropdown",
              width: 4,
              options: [
                "UNSET",
                "self",
                "root",
                "parent",
                "child",
                "collection",
                "item",
                "about",
                "acl",
                "alternate",
                "amphtml",
                "appendix",
                "apple-touch-icon",
                "apple-touch-startup-image",
                "archives",
                "author",
                "blocked-by",
                "bookmark",
                "c2pa-manifest",
                "canonical",
                "chapter",
                "cite-as",
                "collection",
                "compression-dictionary",
                "contents",
                "convertedfrom",
                "copyright",
                "create-form",
                "current",
                "deprecation",
                "describedby",
                "describes",
                "disclosure",
                "dns-prefetch",
                "duplicate",
                "edit",
                "edit-form",
                "edit-media",
                "enclosure",
                "external",
                "first",
                "glossary",
                "help",
                "hosts",
                "hub",
                "ice-server",
                "icon",
                "index",
                "intervalafter",
                "intervalbefore",
                "intervalcontains",
                "intervaldisjoint",
                "intervalduring",
                "intervalequals",
                "intervalfinishedby",
                "intervalfinishes",
                "intervalin",
                "intervalmeets",
                "intervalmetby",
                "intervaloverlappedby",
                "intervaloverlaps",
                "intervalstartedby",
                "intervalstarts",
                "item",
                "last",
                "latest-version",
                "license",
                "linkset",
                "lrdd",
                "manifest",
                "mask-icon",
                "me",
                "media-feed",
                "memento",
                "micropub",
                "modulepreload",
                "monitor",
                "monitor-group",
                "next",
                "next-archive",
                "nofollow",
                "noopener",
                "noreferrer",
                "opener",
                "openid2.local_id",
                "openid2.provider",
                "original",
                "p3pv1",
                "payment",
                "pingback",
                "preconnect",
                "predecessor-version",
                "prefetch",
                "preload",
                "prerender",
                "prev",
                "preview",
                "previous",
                "prev-archive",
                "privacy-policy",
                "profile",
                "publication",
                "related",
                "restconf",
                "replies",
                "ruleinput",
                "search",
                "section",
                "service",
                "service-desc",
                "service-doc",
                "service-meta",
                "sip-trunking-capability",
                "sponsored",
                "start",
                "status",
                "stylesheet",
                "subsection",
                "successor-version",
                "sunset",
                "tag",
                "terms-of-service",
                "timegate",
                "timemap",
                "type",
                "ugc",
                "up",
                "version-history",
                "via",
                "webmention",
                "working-copy",
                "working-copy-of",
              ],
            },
            {
              field: "type",
              name: "Media/MIME Type",
              description:
                "Media type of the referenced entity. For instance 'image/tiff; application=geotiff'. Use 'application/geo+json' for a STAC Item and 'application/json' for STAC Collections and Catalogs.",
              type: "dropdown",
              options: [
                "UNSET",
                "application/json",
                "image/tiff; application=geotiff",
                "image/tiff; application=geotiff; profile=cloud-optimized",
                "image/jp2",
                "image/png",
                "image/jpeg",
                "application/geo+json",
                "application/geo+json-seq",
                "application/geopackage+sqlite3",
                "application/vnd.google-earth.kml+xml",
                "application/vnd.google-earth.kmz",
                "application/x-protobuf",
                "application/vnd.mapbox-vector-tile",
                "application/x-hdf",
                "application/x-hdf5",
                "application/xml",
                "application/ndjson",
                "text/html",
                "text/plain",
                "application/vnd.oai.openapi+json;version=3.0",
                "application/vnd.oai.openapi;version=3.0",
                "application/schema+json",
                "application/pdf",
                "text/csv",
                "application/vnd.apache.parquet",
              ],
              width: 6,
            },
          ],
        },
        {
          field: "temp.editStacCollection.providers",
          name: "Providers",
          description:
            "A list of providers, which may include all organizations capturing or processing the data or the hosting provider.",
          type: "objectarray",
          width: 12,
          object: [
            {
              field: "name",
              name: "Name",
              description:
                "Required - The name of the organization or the individual.",
              type: "text",
              width: 8,
            },
            {
              field: "description",
              name: "Description",
              description:
                "Multi-line description to add further provider information such as processing details for processors and producers, hosting details for hosts or basic contact information.",
              type: "text",
              width: 8,
            },
            {
              field: "roles",
              name: "Roles",
              description:
                "Comma-separated list of roles of the provider. Any of 'licensor', 'producer', 'processor' or 'host'",
              type: "textarray",
              width: 8,
            },
            {
              field: "url",
              name: "URL",
              description:
                "Homepage on which the provider describes the dataset and publishes contact information.",
              type: "text",
              width: 8,
            },
          ],
        },
      ],
    },
    {
      name: "Advanced",
      components: [
        {
          field: "temp.editStacCollection.summaries",
          name: "Summaries",
          description:
            "A map of property summaries, either a set of values, a range of values or a JSON Schema.",
          type: "json",
          width: 12,
          height: "300px",
        },
      ],
    },
  ],
};
