version: "3"
services:
  mmgis:
    image: mmgis:development
    depends_on:
      - mmgis.db
    environment:
      - SERVER=node
      - PORT=8888
      - AUTH=none
      - NODE_ENV=development
      - SECRET=
      - VERBOSE_LOGGING=false
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=MMGIS
      - DB_USER=postgres
      - DB_PASS=somethingsimple
      - HIDE_CONFIG=false
      - CONFIGCONFIG_PATH=
      - FORCE_CONFIG_PATH=
      - FRAME_ANCESTORS=
      - FRAME_SRC=
      - LEADS=["ADMIN"]
      - ENABLE_MMGIS_WEBSOCKETS=true
      - ENABLE_CONFIG_WEBSOCKETS=true
      - ENABLE_CONFIG_OVERRIDE=false
      - MAIN_MISSION=
    volumes:
      - /var/www/html/Missions/:/usr/src/app/Missions
  mmgis.db:
    image: postgis/postgis:10-2.5-alpine
    env_file: .env
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - mmgis-db:/var/lib/postgresql/data
volumes:
  mmgis-db:
