name: mmgis
channels:
  - conda-forge
dependencies:
  - python==3.12
  - gdal==3.12.2
  - geos
  - proj
  - attrs
  - certifi
  - click
  - cligj
  - click-plugins
  - snuggs
  - affine
  - pyparsing
  - colorama
  - pip
  - pip:
      - rasterio>=1.5.0
      - numpy>=2.0.0
      - requests==2.33.0
      - rio_stac>=0.12.0
      - spiceypy==5.1.2
      - pymap3d==3.0.1
      - pypgstac==0.9.6
      - python-dotenv[cli]==1.0.1
      - uvicorn==0.30.6
      - psycopg[binary,pool]==3.2.1
      - stac-fastapi-pgstac==6.2.2
      - tipg==1.3.0
      - titiler.application==0.24.2
      - titiler-pgstac==1.9.0
      - antimeridian==0.3.10
