import $ from 'jquery'
import L_ from '../Layers_/Layers_'
import { toolModules, toolConfigs } from '../../../pre/tools'
import useUIStore from '../UserInterface_/store/uiStore'

let ToolController_ = {
    tools: null,
    activeSeparatedTools: [],
    toolModuleNames: [],
    toolModules: toolModules,
    activeTool: null,
    activeToolName: null,
    _pendingCloseTool: null,
    prevHeight: 0,
    defaultColor: 'var(--color-f)',
    hoverColor: 'var(--color-mmgis)',
    activeColor: 'var(--color-mmgis)',
    activeBG: 'var(--color-i)',
    loaded: false,

    // init: Build the tool module name list and initialize all tool modules.
    // DOM construction for toolbar buttons and separated tools is handled by React
    // (Toolbar.jsx and SeparatedTools.jsx).
    //
    // Tool modules in `toolModules` are now lazy loaders generated by
    // `API/updateTools.js` — each value is a function returning
    // `import('...')`. Tool modules are not materialised until a tool
    // is opened (via `makeTool`) or explicitly preloaded via
    // `ensureToolLoaded`.
    init: function (tools) {
        this.tools = tools

        // Build toolModuleNames array (used by makeTool, getToolsUrl, etc.)
        for (let i = 0; i < tools.length; i++) {
            this.toolModuleNames.push(tools[i].js)
        }

        // Initialize any tool modules that are already loaded synchronously
        // (e.g. modules that ship as object exports rather than lazy loaders).
        // Lazy modules are initialised inside `ensureToolLoaded` after their
        // dynamic import resolves.
        ToolController_.toolModuleNames.forEach((t) => {
            const tm = ToolController_.toolModules[t]
            if (
                tm &&
                typeof tm !== 'function' &&
                typeof tm.initialize === 'function'
            )
                tm.initialize()
        })

        // Publish separated tools list to store (React renders them)
        const separatedTools = tools.filter((t) => t.separatedTool === true)
        useUIStore.getState().setSeparatedToolsList(separatedTools)

        // Auto-open separated tools that have on === true
        separatedTools.forEach((tool) => {
            if (tool.on === true && L_.UserInterface_.isMobile !== true) {
                setTimeout(() => {
                    const toolModuleName = tool.name + 'Tool'
                    ToolController_.ensureToolLoaded(toolModuleName).then(
                        (tM) => {
                            if (tM && tM.made === false) {
                                tM.make(
                                    `toolContentSeparated_${tool.name}`
                                )
                                useUIStore
                                    .getState()
                                    .addActiveSeparatedTool(toolModuleName)
                                ToolController_.activeSeparatedTools.push(
                                    toolModuleName
                                )
                                document.dispatchEvent(
                                    new CustomEvent('toggleSeparatedTool', {
                                        detail: {
                                            toggledToolName: tool.js,
                                            visible: true,
                                        },
                                    })
                                )
                            }
                        }
                    )
                }, 0)
            }
        })

        // Publish tools list to Zustand store for React rendering
        useUIStore.getState().setToolsList(tools)
        useUIStore.getState().setToolsLoaded(true)

        ToolController_.loaded = true
        L_.toolsLoaded = true

        // Kick off lazy-load resolution for any tool whose config has
        // `preload: true`. Cross-tool consumers (Map_ feature clicks,
        // mmgisAPI, LegendTool, …) reach into these tools through
        // `getTool(name).method(...)` and need them resolved.
        ToolController_.preloadEagerTools()

        L_.fullyLoaded()
    },

    clear() {
        // Don't remove #toolbarTools — it's React-managed.
        // Setting toolsLoaded: false (below) causes Toolbar.jsx to unmount it.
        this.tools = null
        this.toolModuleNames = []
        this.activeSeparatedTools = []
        this.toolModules = toolModules
        useUIStore.getState().setSeparatedToolsList([])
        useUIStore.getState().setActiveSeparatedTools([])
        useUIStore.getState().setToolsList([])
        useUIStore.getState().setToolsLoaded(false)
    },
    // Synchronous accessor — preserves the legacy "always returns
    // something method-callable" contract that pre-existed lazy loading.
    //
    // When a tool is lazy-loaded but not yet resolved, `toolModules[name]`
    // is a `() => import(...)` arrow function. Returning that raw
    // function to callers that expect a tool object would crash on
    // `.use()`, `.currentLayer`, `.populateCogScale()`, etc. — so we:
    //   (a) kick off `ensureToolLoaded` in the background so the next
    //       call sees the resolved module, and
    //   (b) return the same `{ use: () => {} }` fallback stub callers
    //       have always received when a tool was missing.
    //
    // Cross-tool dependencies that must always work synchronously
    // should declare `"preload": true` in their `config.json` — those
    // tools are eagerly resolved at startup (see `preloadEagerTools`).
    getTool: function (name) {
        var tool = this.toolModules[name]
        if (!tool) return { use: function () {} }
        if (typeof tool === 'function') {
            // Trigger background resolution; ignore the promise.
            this.ensureToolLoaded(name)
            return { use: function () {} }
        }
        return tool
    },
    // Return the loaded module for `name` or null when it has not yet
    // been materialised. Use this from call sites that synchronously
    // poke at another tool's state (e.g. `LayersTool.orderingHistory`).
    getLoadedTool: function (name) {
        const tm = this.toolModules[name]
        if (!tm || typeof tm === 'function') return null
        return tm
    },
    // Eagerly load every tool whose config sets `preload: true`. Called
    // by `init()` after the synchronous setup has finished so that the
    // tool chunks download in parallel with the rest of the page
    // becoming interactive. Errors are swallowed — a failed preload
    // simply means the tool stays lazy.
    //
    // Source of truth for `preload` is the per-tool `config.json`
    // (exposed via the build-time-generated `toolConfigs` map), NOT
    // mission config — so it can't be turned off accidentally per
    // mission.
    preloadEagerTools: function () {
        Object.keys(toolConfigs || {}).forEach((toolName) => {
            const cfg = toolConfigs[toolName]
            if (!cfg || cfg.preload !== true) return
            // `paths` maps importName -> module path. Eagerly load
            // each import name so all of a tool's modules are
            // available synchronously to cross-tool consumers.
            const paths = cfg.paths || {}
            Object.keys(paths).forEach((importName) => {
                this.ensureToolLoaded(importName)
            })
        })
    },
    // Resolve a lazy tool loader and cache the loaded module in
    // `toolModules[name]`. Returns the loaded module (or null when
    // `name` is unknown). Safe to call repeatedly — the second call
    // simply returns the cached module.
    ensureToolLoaded: async function (name) {
        const current = this.toolModules[name]
        if (!current) return null
        if (typeof current !== 'function') return current
        try {
            const mod = await current()
            const resolved =
                mod && (mod.default !== undefined ? mod.default : mod)
            this.toolModules[name] = resolved
            if (resolved && typeof resolved.initialize === 'function')
                resolved.initialize()
            return resolved
        } catch (err) {
            console.error(`Failed to lazy-load tool '${name}':`, err)
            return null
        }
    },
    makeTool: async function (name, idx) {
        // Resolve the lazy loader (no-op if the module is already
        // loaded). After this await, `toolModules[name]` is the loaded
        // module object.
        await this.ensureToolLoaded(name)
        var tool = this.getTool(name)

        if (tool != undefined) {
            if (this.activeToolName == null || name != this.activeToolName) {
                //change tool
                if (
                    typeof tool.make === 'function' &&
                    typeof tool.destroy === 'function'
                ) {
                    // Destroy the currently active tool before switching
                    if (this.activeTool != null) {
                        this.activeTool.destroy()
                        this.activeTool = null
                    }
                    // If a horizontal tool is still pending close (deferred
                    // destroy via setTimeout), destroy it now before opening
                    // the new tool — otherwise its destroy() is never called.
                    if (this._pendingCloseTool) {
                        this._pendingCloseTool.destroy()
                        this._pendingCloseTool = null
                    }
                    // Cancel any pending horizontal-tool close cleanup
                    ++this._closeSeq

                    this.setToolHeight(tool.height)
                    this.setToolWidth(tool.width)
                    if (tool.height == 0) {
                        this.UserInterface.openToolPanel(tool.width)
                    } else {
                        this.UserInterface.closeToolPanel()
                    }
                    // Toggle drag handle via store (React is single source of truth)
                    useUIStore.getState().setToolPanelDragVisible(
                        toolConfigs[ToolController_.tools[idx].name]
                            ?.expandable === true
                    )

                    // On mobile, rescue #timeUI back to staging before the new
                    // tool's make() clears #tools — the React useEffect in
                    // MobileTimeUIToggle fires too late (async) to save it.
                    if (useUIStore.getState().isMobile) {
                        const timeUI = document.getElementById('timeUI')
                        const staging = document.getElementById(
                            'timeUIMobileStaging'
                        )
                        if (timeUI && staging && timeUI.closest('#tools')) {
                            staging.appendChild(timeUI)
                        }
                        useUIStore.getState().setTimeUIActive(false)
                        useUIStore.getState().setTimeUIExpanded(false)
                    }

                    this.activeTool = tool
                    tool.make(this)

                    // Inject close X button into the tool's content area
                    ToolController_.injectCloseButton()
                } else {
                    console.warn(
                        'WARNING: ' +
                            name +
                            ' does not have a make or destroy function.' +
                            " All tools require a 'make' and a 'destroy' function."
                    )
                }
                this.activeToolName = name
            } else {
                // Toggle drag handle via store (React is single source of truth)
                useUIStore.getState().setToolPanelDragVisible(false)
                //close tool
                this.closeActiveTool()
            }
        }
    },
    setToolHeight: function (newHeight) {
        if (this.prevHeight != newHeight && this.UserInterface != null) {
            this.UserInterface.setToolHeight(newHeight)
        }
        this.prevHeight = newHeight
    },
    setToolWidth: function (newWidth) {
        newWidth = newWidth || 'full'
        this.UserInterface.setToolWidth(newWidth)
    },
    notifyActiveTool: function (type, payload) {
        if (this.activeTool != null) {
            if (typeof this.activeTool.notify === 'function')
                this.activeTool.notify(type, payload)
        }
    },
    _closeSeq: 0,
    closeActiveTool: function () {
        // Button active/inactive styling is now driven by the Zustand store's
        // activeToolName field. Toolbar.jsx reads it and passes isActive to
        // each ToolButton, so no imperative DOM class toggling is needed here.
        // Setting activeToolName to null (below) triggers React to re-render
        // all buttons with isActive=false.

        var wasHorizontal = this.prevHeight != 0

        if (this.activeTool != null) {
            if (wasHorizontal) {
                // Horizontal tools: animate the wrapper height to 0 first,
                // then destroy the tool and clean up after the CSS transition
                // (0.4s ease-out) completes. This keeps the tool content
                // visible while the wrapper slides downward.
                var closingTool = this.activeTool
                this._pendingCloseTool = closingTool
                var closeId = ++this._closeSeq
                this.UserInterface.setToolHeight(0)
                // Reset wrapper width immediately so TopBar snaps to
                // the correct position at the start of the close animation
                // (the height animation provides the visual close effect).
                useUIStore.setState({
                    toolsWrapperRawWidth: 0,
                    toolsWrapperCSSWidth: '0%',
                })
                setTimeout(function () {
                    // Guard: if another tool was opened during the transition,
                    // _closeSeq will have incremented — skip stale cleanup.
                    if (ToolController_._closeSeq !== closeId) return
                    try {
                        closingTool.destroy()
                    } catch (e) {
                        console.warn('Deferred tool destroy() failed:', e)
                    }
                    ToolController_._pendingCloseTool = null
                    var toolsEl = document.getElementById('tools')
                    if (toolsEl) toolsEl.innerHTML = ''
                }, 420)
            } else {
                // Vertical/side-panel tools: destroy immediately
                this.activeTool.destroy()
                var toolsEl = document.getElementById('tools')
                if (toolsEl) toolsEl.innerHTML = ''
                this.UserInterface.closeToolPanel()
                useUIStore.setState({
                    toolsWrapperRawWidth: 0,
                    toolsWrapperCSSWidth: '0%',
                })
                if (this.UserInterface != null) {
                    this.UserInterface.setToolHeight(0)
                }
            }
        }
        this.activeTool = null
        this.activeToolName = null
        // Sync to store so React re-renders button states
        useUIStore.getState().setActiveToolName(null)
        useUIStore.getState().setToolPanelDragVisible(false)
        this.prevHeight = 0
    },
    injectCloseButton: function () {
        // Horizontal tools: close button is rendered by the React
        // BottomFloatingBar component (SplitScreens.jsx) — no injection
        // needed here. Only inject for vertical (side-panel) tools.
        const isHorizontal = this.activeTool && this.activeTool.height > 0
        if (isHorizontal) return

        const container = $('#toolPanel')
        if (!container.length) return

        // Remove any existing injected close button
        container.find('.tool-close-btn').remove()

        const closeBtn = $('<div>')
            .addClass('tool-close-btn')
            .attr('title', 'Close Tool')
            .css({
                position: 'absolute',
                top: '6px',
                right: '6px',
                width: '26px',
                height: '26px',
                display: 'flex',
                'align-items': 'center',
                'justify-content': 'center',
                cursor: 'pointer',
                'border-radius': '4px',
                'z-index': '10',
                color: '#9ca3af',
                'font-size': '18px',
                transition: 'background 0.15s, color 0.15s',
            })
            .html("<i class='mdi mdi-close mdi-18px'></i>")
            .on('mouseenter', function () {
                $(this).css({ background: 'rgba(255,255,255,0.1)', color: '#fff' })
            })
            .on('mouseleave', function () {
                $(this).css({ background: 'transparent', color: '#9ca3af' })
            })
            .on('click', function () {
                ToolController_.closeActiveTool()
            })

        // Ensure the container has position:relative for absolute positioning
        const firstChild = container.children().first()
        if (firstChild.length) {
            firstChild.css('position', 'relative')
            firstChild.append(closeBtn)
        } else {
            container.css('position', 'relative')
            container.append(closeBtn)
        }
    },
    getToolsUrl: function () {
        var toolsUrl = ''
        // Walk every loaded tool module (lazy loaders without a
        // resolved module yet have no URL state to serialise).
        for (var i = 0; i < this.toolModuleNames.length; i++) {
            var tool = this.toolModules[this.toolModuleNames[i]]
            if (
                tool &&
                typeof tool !== 'function' &&
                typeof tool.getUrlString === 'function'
            ) {
                var urlString = tool.getUrlString()
                if (urlString.length > 0)
                    toolsUrl += this.toolModuleNames[i] + '$' + urlString + ','
            }
        }
        //get rid of last , if there is one
        if (toolsUrl[toolsUrl.length - 1] == ',')
            toolsUrl = toolsUrl.substr(0, toolsUrl.length - 1)

        if (toolsUrl.length == 0) toolsUrl = false
        return toolsUrl
    },
    fina: function (userinterface) {
        this.UserInterface = userinterface
    },
    finalizeTools: function () {
        for (let i = 0; i < this.toolModuleNames.length; i++) {
            const tool = this.toolModules[this.toolModuleNames[i]]
            if (
                tool &&
                typeof tool !== 'function' &&
                typeof tool.finalize === 'function'
            ) {
                tool.finalize()
            }
        }

        // Open separated tools with displayOnStart after all layers are loaded
        if (L_.UserInterface_.isMobile !== true) {
            const separatedTools = useUIStore.getState().separatedToolsList
            separatedTools.forEach((tool) => {
                const toolModuleName = tool.name + 'Tool'
                ToolController_.ensureToolLoaded(toolModuleName).then(
                    (tM) => {
                        if (
                            tM &&
                            tM.displayOnStart === true &&
                            tM.made === false
                        ) {
                            setTimeout(() => {
                                tM.make(`toolContentSeparated_${tool.name}`)
                                ToolController_.activeSeparatedTools.push(
                                    toolModuleName
                                )
                                useUIStore
                                    .getState()
                                    .addActiveSeparatedTool(toolModuleName)
                                document.dispatchEvent(
                                    new CustomEvent('toggleSeparatedTool', {
                                        detail: {
                                            toggledToolName: tool.js,
                                            visible: true,
                                        },
                                    })
                                )
                            }, 0)
                        }
                    }
                )
            })
        }
    },
}

window.ToolController_ = ToolController_
export default ToolController_
