import $ from 'jquery'
import L_ from '../Layers_/Layers_'
import { toolModules, toolConfigs } from '../../../pre/tools'
import useUIStore from '../UserInterface_/store/uiStore'
import { getSeparatedMode, resolveToolJs } from './toolControllerHelpers'

// Once per name: a miss is usually in a click handler, so warning every time
// would be a console full of the same line.
const _warnedMissingTools = new Set()

let ToolController_ = {
    tools: null,
    activeSeparatedTools: [],
    toolModuleNames: [],
    toolModules: toolModules,
    activeTool: null,
    activeToolName: null,
    _pendingCloseTool: null,
    prevHeight: 0,
    defaultColor: 'var(--color-f)',
    hoverColor: 'var(--color-mmgis)',
    activeColor: 'var(--color-mmgis)',
    activeBG: 'var(--color-i)',
    loaded: false,

    // init: Build the tool module name list and initialize all tool modules.
    // DOM construction for toolbar buttons and separated tools is handled by React
    // (Toolbar.jsx and SeparatedTools.jsx).
    init: function (tools) {
        this.tools = tools

        // Build toolModuleNames array (used by makeTool, getToolsUrl, etc.)
        for (let i = 0; i < tools.length; i++) {
            this.toolModuleNames.push(tools[i].js)
        }

        // Initialize tool modules. `toolModules` is populated by
        // `src/pre/tools.js` (generated by `API/updateTools.js`) with
        // static imports — every entry is an already-loaded module.
        ToolController_.toolModuleNames.forEach((t) => {
            const tm = ToolController_.toolModules[t]
            if (tm && typeof tm.initialize === 'function') tm.initialize()
        })

        // separatedTool is defined solely by the plugin manifest (toolConfigs),
        // like `expandable`. `true` = framed panel, "custom" = chrome-less
        // (tool owns its DOM); anything else (incl. unset) = not separated.
        const separatedTools = tools.filter((t) => {
            const raw = toolConfigs[t.name]?.separatedTool
            if (raw != null && !getSeparatedMode(toolConfigs, t.name)) {
                console.warn(
                    `Tool "${t.name}" has an unrecognized separatedTool value ${JSON.stringify(
                        raw
                    )}; expected true or "custom". Treating it as not separated.`
                )
            }
            return getSeparatedMode(toolConfigs, t.name) != null
        })
        useUIStore.getState().setSeparatedToolsList(separatedTools)

        // Auto-open separated tools that have on === true
        separatedTools.forEach((tool) => {
            if (tool.on === true && L_.UserInterface_.isMobile !== true) {
                setTimeout(() => {
                    const toolModuleName = tool.name + 'Tool'
                    const tM = ToolController_.toolModules[toolModuleName]
                    if (tM && tM.made === false) {
                        tM.make(`toolContentSeparated_${tool.name}`)
                        useUIStore
                            .getState()
                            .addActiveSeparatedTool(toolModuleName)
                        ToolController_.activeSeparatedTools.push(
                            toolModuleName
                        )
                        document.dispatchEvent(
                            new CustomEvent('toggleSeparatedTool', {
                                detail: {
                                    toggledToolName: tool.js,
                                    visible: true,
                                },
                            })
                        )
                    }
                }, 0)
            }
        })

        // Publish tools list to Zustand store for React rendering
        useUIStore.getState().setToolsList(tools)
        useUIStore.getState().setToolsLoaded(true)

        ToolController_.loaded = true
        L_.toolsLoaded = true

        L_.fullyLoaded()
    },

    clear() {
        // Don't remove #toolbarTools — it's React-managed.
        // Setting toolsLoaded: false (below) causes Toolbar.jsx to unmount it.
        this.tools = null
        this.toolModuleNames = []
        this.activeSeparatedTools = []
        this.toolModules = toolModules
        useUIStore.getState().setSeparatedToolsList([])
        useUIStore.getState().setActiveSeparatedTools([])
        useUIStore.getState().setToolsList([])
        useUIStore.getState().setToolsLoaded(false)
    },
    getTool: function (name) {
        var tool = this.toolModules[name]
        if (tool == null && !_warnedMissingTools.has(name)) {
            // The stub keeps a caller from throwing, but silence turns "the
            // tool isn't in this mission's toolbar" into "my plugin does
            // nothing", which is the harder thing to debug.
            _warnedMissingTools.add(name)
            console.warn(
                `ToolController_.getTool('${name}'): no such tool is loaded — calls on it do nothing. Is it in the mission's toolbar and enabled?`
            )
        }
        return tool || { use: function () {} }
    },
    // openTool/closeTool — type-agnostic public API (keyed by tool name, e.g.
    // 'Identifier') so plugins have one call regardless of tool kind. Both
    // no-op if the tool is already in the requested state.
    openTool: function (name) {
        if (getSeparatedMode(toolConfigs, name)) {
            const toolModuleName = name + 'Tool'
            const tM = this.toolModules[toolModuleName]
            if (!tM || tM.made === true) return
            tM.make(`toolContentSeparated_${name}`)
            this.activeSeparatedTools.push(toolModuleName)
            useUIStore.getState().addActiveSeparatedTool(toolModuleName)
            document.dispatchEvent(
                new CustomEvent('toggleSeparatedTool', {
                    detail: {
                        toggledToolName: resolveToolJs(this.tools, name),
                        visible: true,
                    },
                })
            )
        } else {
            const idx = (this.tools || []).findIndex((t) => t.name === name)
            if (idx < 0) return
            const toolModuleName = this.toolModuleNames[idx]
            if (this.activeToolName === toolModuleName) return
            this.makeTool(toolModuleName, idx)
            useUIStore.getState().setActiveToolName(this.activeToolName)
            document.dispatchEvent(
                new CustomEvent('toolChange', {
                    detail: {
                        activeTool: this.activeTool,
                        activeToolName: this.activeToolName,
                    },
                })
            )
        }
    },
    closeTool: function (name) {
        if (getSeparatedMode(toolConfigs, name)) {
            const toolModuleName = name + 'Tool'
            const tM = this.toolModules[toolModuleName]
            if (!tM || tM.made === false) return
            tM.destroy()
            this.activeSeparatedTools = this.activeSeparatedTools.filter(
                (a) => a !== toolModuleName
            )
            useUIStore.getState().removeActiveSeparatedTool(toolModuleName)
            document.dispatchEvent(
                new CustomEvent('toggleSeparatedTool', {
                    detail: {
                        toggledToolName: resolveToolJs(this.tools, name),
                        visible: false,
                    },
                })
            )
        } else {
            const idx = (this.tools || []).findIndex((t) => t.name === name)
            if (idx < 0) return
            if (this.activeToolName === this.toolModuleNames[idx]) {
                this.closeActiveTool()
                document.dispatchEvent(
                    new CustomEvent('toolChange', {
                        detail: {
                            activeTool: this.activeTool,
                            activeToolName: this.activeToolName,
                        },
                    })
                )
            }
        }
    },
    makeTool: function (name, idx) {
        var tool = this.getTool(name)

        if (tool != undefined) {
            if (this.activeToolName == null || name != this.activeToolName) {
                //change tool
                if (
                    typeof tool.make === 'function' &&
                    typeof tool.destroy === 'function'
                ) {
                    // Destroy the currently active tool before switching
                    if (this.activeTool != null) {
                        this.activeTool.destroy()
                        this.activeTool = null
                    }
                    // If a horizontal tool is still pending close (deferred
                    // destroy via setTimeout), destroy it now before opening
                    // the new tool — otherwise its destroy() is never called.
                    if (this._pendingCloseTool) {
                        this._pendingCloseTool.destroy()
                        this._pendingCloseTool = null
                    }
                    // Cancel any pending horizontal-tool close cleanup
                    ++this._closeSeq

                    this.setToolHeight(tool.height)
                    this.setToolWidth(tool.width)
                    if (tool.height == 0) {
                        this.UserInterface.openToolPanel(tool.width)
                    } else {
                        this.UserInterface.closeToolPanel()
                    }
                    // Toggle drag handle via store (React is single source of truth)
                    useUIStore.getState().setToolPanelDragVisible(
                        toolConfigs[ToolController_.tools[idx].name]
                            ?.expandable === true
                    )

                    // On mobile, rescue #timeUI back to staging before the new
                    // tool's make() clears #tools — the React useEffect in
                    // MobileTimeUIToggle fires too late (async) to save it.
                    if (useUIStore.getState().isMobile) {
                        const timeUI = document.getElementById('timeUI')
                        const staging = document.getElementById(
                            'timeUIMobileStaging'
                        )
                        if (timeUI && staging && timeUI.closest('#tools')) {
                            staging.appendChild(timeUI)
                        }
                        useUIStore.getState().setTimeUIActive(false)
                        useUIStore.getState().setTimeUIExpanded(false)
                    }

                    this.activeTool = tool
                    tool.make(this)

                    // Inject close X button into the tool's content area
                    ToolController_.injectCloseButton()
                } else {
                    console.warn(
                        'WARNING: ' +
                            name +
                            ' does not have a make or destroy function.' +
                            " All tools require a 'make' and a 'destroy' function."
                    )
                }
                this.activeToolName = name
            } else {
                // Toggle drag handle via store (React is single source of truth)
                useUIStore.getState().setToolPanelDragVisible(false)
                //close tool
                this.closeActiveTool()
            }
        }
    },
    setToolHeight: function (newHeight) {
        if (this.prevHeight != newHeight && this.UserInterface != null) {
            this.UserInterface.setToolHeight(newHeight)
        }
        this.prevHeight = newHeight
    },
    setToolWidth: function (newWidth) {
        newWidth = newWidth || 'full'
        this.UserInterface.setToolWidth(newWidth)
    },
    notifyActiveTool: function (type, payload) {
        if (this.activeTool != null) {
            if (typeof this.activeTool.notify === 'function')
                this.activeTool.notify(type, payload)
        }
    },
    _closeSeq: 0,
    closeActiveTool: function () {
        // Button active/inactive styling is now driven by the Zustand store's
        // activeToolName field. Toolbar.jsx reads it and passes isActive to
        // each ToolButton, so no imperative DOM class toggling is needed here.
        // Setting activeToolName to null (below) triggers React to re-render
        // all buttons with isActive=false.

        var wasHorizontal = this.prevHeight != 0

        if (this.activeTool != null) {
            if (wasHorizontal) {
                // Horizontal tools: animate the wrapper height to 0 first,
                // then destroy the tool and clean up after the CSS transition
                // (0.4s ease-out) completes. This keeps the tool content
                // visible while the wrapper slides downward.
                var closingTool = this.activeTool
                this._pendingCloseTool = closingTool
                var closeId = ++this._closeSeq
                this.UserInterface.setToolHeight(0)
                // Reset wrapper width immediately so TopBar snaps to
                // the correct position at the start of the close animation
                // (the height animation provides the visual close effect).
                useUIStore.setState({
                    toolsWrapperRawWidth: 0,
                    toolsWrapperCSSWidth: '0%',
                })
                setTimeout(function () {
                    // Guard: if another tool was opened during the transition,
                    // _closeSeq will have incremented — skip stale cleanup.
                    if (ToolController_._closeSeq !== closeId) return
                    try {
                        closingTool.destroy()
                    } catch (e) {
                        console.warn('Deferred tool destroy() failed:', e)
                    }
                    ToolController_._pendingCloseTool = null
                    var toolsEl = document.getElementById('tools')
                    if (toolsEl) toolsEl.innerHTML = ''
                }, 420)
            } else {
                // Vertical/side-panel tools: destroy immediately
                this.activeTool.destroy()
                var toolsEl = document.getElementById('tools')
                if (toolsEl) toolsEl.innerHTML = ''
                this.UserInterface.closeToolPanel()
                useUIStore.setState({
                    toolsWrapperRawWidth: 0,
                    toolsWrapperCSSWidth: '0%',
                })
                if (this.UserInterface != null) {
                    this.UserInterface.setToolHeight(0)
                }
            }
        }
        this.activeTool = null
        this.activeToolName = null
        // Sync to store so React re-renders button states
        useUIStore.getState().setActiveToolName(null)
        useUIStore.getState().setToolPanelDragVisible(false)
        this.prevHeight = 0
    },
    injectCloseButton: function () {
        // Horizontal tools: close button is rendered by the React
        // BottomFloatingBar component (SplitScreens.jsx) — no injection
        // needed here. Only inject for vertical (side-panel) tools.
        const isHorizontal = this.activeTool && this.activeTool.height > 0
        if (isHorizontal) return

        const container = $('#toolPanel')
        if (!container.length) return

        // Remove any existing injected close button
        container.find('.tool-close-btn').remove()

        const closeBtn = $('<div>')
            .addClass('tool-close-btn')
            .attr('title', 'Close Tool')
            .css({
                position: 'absolute',
                top: '6px',
                right: '6px',
                width: '26px',
                height: '26px',
                display: 'flex',
                'align-items': 'center',
                'justify-content': 'center',
                cursor: 'pointer',
                'border-radius': '4px',
                'z-index': '10',
                color: '#9ca3af',
                'font-size': '18px',
                transition: 'background 0.15s, color 0.15s',
            })
            .html("<i class='mdi mdi-close mdi-18px'></i>")
            .on('mouseenter', function () {
                $(this).css({ background: 'rgba(255,255,255,0.1)', color: '#fff' })
            })
            .on('mouseleave', function () {
                $(this).css({ background: 'transparent', color: '#9ca3af' })
            })
            .on('click', function () {
                ToolController_.closeActiveTool()
            })

        // Ensure the container has position:relative for absolute positioning
        const firstChild = container.children().first()
        if (firstChild.length) {
            firstChild.css('position', 'relative')
            firstChild.append(closeBtn)
        } else {
            container.css('position', 'relative')
            container.append(closeBtn)
        }
    },
    getToolsUrl: function () {
        var toolsUrl = ''
        // Walk every loaded tool module (lazy loaders without a
        // resolved module yet have no URL state to serialise).
        for (var i = 0; i < this.toolModuleNames.length; i++) {
            var tool = this.toolModules[this.toolModuleNames[i]]
            if (
                tool &&
                typeof tool !== 'function' &&
                typeof tool.getUrlString === 'function'
            ) {
                var urlString = tool.getUrlString()
                if (urlString.length > 0)
                    toolsUrl += this.toolModuleNames[i] + '$' + urlString + ','
            }
        }
        //get rid of last , if there is one
        if (toolsUrl[toolsUrl.length - 1] == ',')
            toolsUrl = toolsUrl.substr(0, toolsUrl.length - 1)

        if (toolsUrl.length == 0) toolsUrl = false
        return toolsUrl
    },
    fina: function (userinterface) {
        this.UserInterface = userinterface
    },
    finalizeTools: function () {
        for (let i = 0; i < this.toolModuleNames.length; i++) {
            const tool = this.toolModules[this.toolModuleNames[i]]
            if (
                tool &&
                typeof tool !== 'function' &&
                typeof tool.finalize === 'function'
            ) {
                tool.finalize()
            }
        }

        // Open separated tools with displayOnStart after all layers are loaded
        if (L_.UserInterface_.isMobile !== true) {
            const separatedTools = useUIStore.getState().separatedToolsList
            separatedTools.forEach((tool) => {
                const toolModuleName = tool.name + 'Tool'
                const tM = ToolController_.toolModules[toolModuleName]
                if (
                    tM &&
                    tM.displayOnStart === true &&
                    tM.made === false
                ) {
                    setTimeout(() => {
                        tM.make(`toolContentSeparated_${tool.name}`)
                        ToolController_.activeSeparatedTools.push(
                            toolModuleName
                        )
                        useUIStore
                            .getState()
                            .addActiveSeparatedTool(toolModuleName)
                        document.dispatchEvent(
                            new CustomEvent('toggleSeparatedTool', {
                                detail: {
                                    toggledToolName: tool.js,
                                    visible: true,
                                },
                            })
                        )
                    }, 0)
                }
            })
        }
    },
}

window.ToolController_ = ToolController_
export default ToolController_
