module.exports = {
  msv: {
    mission: "Test",
    site: "",
    masterdb: false,
    view: ["0", "0", "0"],
    radius: {
      major: "3396190",
      minor: "3396190",
    },
    mapscale: "",
  },
  projection: {
    custom: false,
    epsg: "",
    proj: "",
    globeproj: "webmercator",
    xmlpath: "",
    bounds: ["", "", "", ""],
    origin: ["", ""],
    reszoomlevel: "",
    resunitsperpixel: "",
  },
  look: {
    pagename: "MMGIS",
    minimalist: false,
    topbar: true,
    toolbar: true,
    scalebar: true,
    coordinates: true,
    zoomcontrol: false,
    graticule: false,
    miscellaneous: true,
    bodycolor: "",
    topbarcolor: "",
    toolbarcolor: "",
    mapcolor: "",
    swap: true,
    copylink: true,
    screenshot: true,
    fullscreen: true,
    help: true,
    logourl: "",
    helpurl: "",
  },
  panels: ["viewer", "map", "globe"],
  time: ["enabled"],
  tools: [
    {
      name: "Layers",
      icon: "layers",
      js: "LayersTool",
    },
    {
      name: "Legend",
      icon: "format-list-bulleted-type",
      js: "LegendTool",
    },
    {
      name: "Info",
      icon: "information-variant",
      js: "InfoTool",
    },
  ],
  layers: [],
};
